### ISSUE TITLE
BeSLab instance affiliation process to BeSecure Community Lab

### ISSUE THREAD

**Issue by harimohanr** [Be-Secure/BeSLab#5]
The BeSLab instance is a registered Open Source Assurance Provider (OSAP). BeSecure Community Lab maintains the registry of all affiliated BeSLab instnace across the world. Build the logic in the blueprint to have a OSAP registry and the mechanism to affiliate a new lab to BeSecure Community Lab. Also, there should be a way to remove the affiliation of a lab.

**Comment by anilsingla** [comment]
Completed.
